AB#297 Create test scripts for TCs of US5
tuanna0308/poc-project-automation pull request #15
Opened 2023-01-06 06:20 UTC by NhiChung

- [x] Automated TCs of US5
- [x] Added _switchToLastTab() switchToFirstTab()  methods into **BasePage**
- [x] Updated TestNG version 6. to 7.1.0

2023-01-09 07:33 UTC, khiemkao requested changes
please double check

2023-01-09 07:33 UTC, khiemkao commented on src/main/java/com/epam/poc/configs/browsers/ChromeBrowser.java
> +import org.openqa.selenium.PageLoadStrategy;
remove the unused import

2023-01-09 07:33 UTC, khiemkao commented on src/main/java/com/epam/poc/pageObjects/HeaderPageObject.java
> +    @Step("Go to Sell Center page after click on 'Seller Center' item on the top left menu header")
can be shortened by "Go to Sell Center page from top left menu header"

2023-01-09 07:33 UTC, khiemkao commented on src/main/java/com/epam/poc/pageObjects/HeaderPageObject.java
> +    @Step("Go to Join as Seller page after click on 'Join as Seller' item on the top left menu header")
same as above

2023-01-09 07:33 UTC, khiemkao commented on src/main/java/com/epam/poc/pageObjects/HeaderPageObject.java
> +    @Step("Go to Follow us on Facebook page after click on 'Follow us on Facebook link' item on the top left menu header")
same as above

2023-01-09 07:33 UTC, khiemkao commented on src/main/java/com/epam/poc/pageObjects/HeaderPageObject.java
> +    @Step("Go to Follow us on Instagram page after click on 'Follow us on Instagram link' item on the top left menu header")
same as above

2023-01-09 07:33 UTC, khiemkao commented on src/main/java/com/epam/poc/pageObjects/HeaderPageObject.java
> +    @Step("Go to Download page after click on 'Download' item on the top left menu header")
same as above

2023-01-09 07:33 UTC, khiemkao commented on src/main/java/com/epam/poc/pageObjects/HeaderPageObject.java
> +    @Step("Hover the Download item on the top left menu header then check if the QR code is displayed")
not matching the step description and actions below.
this can be implemented as 
```
@step("verify QR code from Top left menu header")
public boolean verifyQRcodeFromMenuHeader() {
     hoverElement(driver, downloadLink);
     // you can add wait if needed
     return isElementDisplayed(driver, <QR_locator>);
}
```

2023-01-09 07:33 UTC, khiemkao commented on src/test/java/com/epam/poc/homePage/TopLeftNavigationMenuTest.java
> +        headerPage.switchToPreviousTab(driver);
try moving `headerPage.switchToPreviousTab(driver);` to @AfterMethod
because if the assertion is failed, this step will not be executed. and then your next tests will be failed.

2023-01-10 04:11 UTC, NhiChung commented
Hi team, this PR is ready to merge 
report: 
![image](https://user-images.githubusercontent.com/92297341/211460071-938067ae-1ad8-42c3-844f-ddb89ee2ed44.png)

When I resolve the conflict, I accepted both codes below
<img width="496" alt="image" src="https://user-images.githubusercontent.com/92297341/211459996-da7ed12f-190e-47dd-b756-d8203bfae3bb.png">

2023-01-10 06:16 UTC, tuanna0308 reviewed
Please check my comment, thanks!

2023-01-10 06:16 UTC, tuanna0308 commented on src/main/java/com/epam/poc/commons/BasePage.java
> +    public void switchToPreviousTab(WebDriver driver) {
Hi Nhi, you should change the name of method to "switchToFirstTab" because of this command "driver.switchTo().window(tabs.get(0))"

2023-01-10 06:16 UTC, tuanna0308 commented on src/main/java/com/epam/poc/commons/BasePage.java
> +    public void switchToNewTab(WebDriver driver) {
You should change the name of the method to "switchToLastTab" because this command "driver.switchTo().window(tabs.get(tabs.size() - 1))".
Imagine you have multiple tabs, so by your command, it will switch to the last tab.

2023-01-11 02:16 UTC, tuanna0308 commented on src/main/java/com/epam/poc/pageUIs/HeaderPageUI.java
> +    public static final By followUsOnFacebookLink = By.cssSelector("[title*='Facebook']");
Hi Nhi, you should rename these variables with an uppercase letter.
Ex: "followUsOnFacebookLink " => "FOLLOW_US_ON_FACEBOOK_LINK_BY"

2023-01-11 03:31 UTC, khiemkao approved these changes

2023-01-11 06:46 UTC, tuanna0308 approved these changes
I am ok with this change, will merge it into the master, thanks @NhiChung for your hard work!

2023-01-11 06:46 UTC, merged