#81 categories list section
tuanna0308/poc-project-automation pull request #19
Opened 2023-01-09 10:19 UTC by DucLe8

Local result: 
![image](https://user-images.githubusercontent.com/105845413/211283859-200dd6e6-0ca5-4cd8-a9b7-5c49036e81c7.png)

2023-01-09 10:57 UTC, khiemkao requested changes

2023-01-09 10:57 UTC, khiemkao commented on src/test/java/com/epam/poc/homePage/CategoriesListSectionTest.java
> +        categoriesListSection.waitForElementContainsText(driver, searchField, expectedCategory);
suggest moving lines 39 to 43 and line 49 to PageObject.
in the test class, should avoid calling out the PageUI elements.

2023-01-09 10:57 UTC, khiemkao commented on src/test/java/com/epam/poc/homePage/CategoriesListSectionTest.java
> +        categoriesListSection.waitForElementContainsText(driver, searchField, expectedCategory);
same as above

2023-01-10 04:50 UTC, DucLe8 commented
Fixed 2 comments from anh @khiemkao. Ready to review now

2023-01-10 06:09 UTC, tuanna0308 reviewed
Please check my comment

2023-01-10 06:09 UTC, tuanna0308 commented on src/test/java/com/epam/poc/homePage/CategoriesListSectionTest.java
> +    @Parameters({"pageUrl"})
you can remove this parameter since you didn't use in your code

2023-01-10 06:09 UTC, tuanna0308 commented on src/test/java/com/epam/poc/homePage/CategoriesListSectionTest.java
> +    @Parameters({"pageUrl"})
same as above

2023-01-10 07:20 UTC, DucLe8 commented
Updated anh @tuanna0308

2023-01-11 02:18 UTC, tuanna0308 approved these changes
Looks good for me, approved

2023-01-11 03:26 UTC, khiemkao approved these changes

2023-01-11 03:27 UTC, merged